spring:
  application:
    name: spring-mv
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace